
/*******************************************************************************
* generated by lcd-image-converter rev.e3ba1ed from 2025-01-31 18:27:03 +0500
* image
* filename: unsaved
* name: 2x2
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/


#ifndef TIMAGE_DEFINED
#define TIMAGE_DEFINED
typedef struct {
    const uint8_t *data;
    uint16_t width;
    uint16_t height;
    uint8_t dataSize;
} tImage;
#endif

#include <stdint.h>



static const uint8_t image_data_2x2[2] = {
    // ██
    // ██
    0xc0, 0xc0
};
const tImage flake2 = { image_data_2x2, 2, 2, 8 };

